name: Lint and Test

on:
  push:
    # run this on every branch except gh-pages
    branches-ignore:
      - gh-pages
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.2
        with:
          node-version: 12.x

      - name: Build static web app bundle
        run: |
          cd octotramp-client
          yarn install
          yarn webpack

      - name: Lint TypeScript using prettier
        run: node ./octotramp-client/node_modules/.bin/prettier --check ./octotramp-client/src

